name: Deploy to ECS
on:
  push:
    branches:
      - main
    paths:
      - 'ECS/**'
env:
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4

      - name: Initialize Terraform
        run: |
          terraform init
           terraform validate
            
      - name: Plan Terraform changes
        run: |
          terraform plan -out=tfplan

      - name: Wait for approval before applying changes
        id: wait_for_approval
        uses: trstringer/manual-approval@v1
        with:
            timeout: 3600 # 1 hour
            message: "Please approve the deployment to ECS."
    
      - name: Apply Terraform changes
        if: steps.wait_for_approval.outputs.approved == 'true'
        run: |
          terraform apply -auto-approve tfplan      
    
        
